eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: clientName
server:
  port: 8089
spring:
  application:
    name: a-bootiful-client